spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http//admin:local123@localhost:8888"
  cloud:
    config:
      username: admin
      password: local123
      profile: dev
      label: main

